language: csharp
mono:
  - latest
solution: ./ZenCashier/ZenCashier.sln
install:
  - nuget restore ./ZenCashier/ZenCashier.sln
  - nuget install xunit.runner.console -Version 2.4.1 -OutputDirectory ./testrunner
script:
  - msbuild /p:Configuration=Release ./ZenCashier/ZenCashier.sln
  - mono /home/travis/build/jdmac020/zenCashier/ZenCashier/packages/xunit.runner.console.2.4.1/tools/net461/xunit.console.exe /home/travis/build/jdmac020/zenCashier/ZenCashier/ZenCashier/bin/Release/ZenCashier.dll                                                                                                                              
deploy:
  provider: releases
  api_key: 0aa3e603053ddc94b4b87ffeb3897c8531e50dd0
  file: ./ZenCashier/bin/Release/ZenCashier.dll
  skip_cleanup: true
  on:
    tags: true
# Just a change for the season