language: csharp
mono:
  - latest
solution: ./ZenCashier/ZenCashier.sln
install:
  - nuget restore ./ZenCashier/ZenCashier.sln
script:
  - msbuild /p:Configuration=Release ./ZenCashier/ZenCashier.sln
  - mono ./testrunner/xunit.runner.2.4.1/tools/net461/xunit.console.exe ./ZenCashier/bin/Release/ZenCashier.dll